const servantList = [{"id": 2, "name": "Altria Pendragon", "class": "saber", "rarity": "ssr", "available": "permanent"},
                    {"id": 3, "name": "Altria Pendragon (Alter)", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 4, "name": "Altria Pendragon (Lily)", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 5, "name": "Nero Claudius", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 6, "name": "Siegfried", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 7, "name": "Gaius Julius Caesar", "class": "saber", "rarity": "r", "available": "permanent"},
                    {"id": 8, "name": "Altera", "class": "saber", "rarity": "ssr", "available": "permanent"},
                    {"id": 9, "name": "Gilles de Rais (Saber)", "class": "saber", "rarity": "r", "available": "permanent"},
                    {"id": 10, "name": "Chevalier d'Eon", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 11, "name": "EMIYA", "class": "archer", "rarity": "sr", "available": "permanent"},
                    {"id": 12, "name": "Gilgamesh", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 13, "name": "Robin Hood", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 14, "name": "Atalanta", "class": "archer", "rarity": "sr", "available": "permanent"},
                    {"id": 15, "name": "Euryale", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 16, "name": "Arash", "class": "archer", "rarity": "c", "available": "permanent"},
                    {"id": 17, "name": "Cu Chulainn", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 18, "name": "Elizabeth Bathory", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 19, "name": "Musashibou Benkei", "class": "lancer", "rarity": "uc", "available": "permanent"},
                    {"id": 20, "name": "Cu Chulainn (Prototype)", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 21, "name": "Leonidas I", "class": "lancer", "rarity": "uc", "available": "permanent"},
                    {"id": 22, "name": "Romulus", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 23, "name": "Medusa", "class": "rider", "rarity": "r", "available": "permanent"},
                    {"id": 24, "name": "Georgios", "class": "rider", "rarity": "uc", "available": "permanent"},
                    {"id": 25, "name": "Edward Teach", "class": "rider", "rarity": "uc", "available": "permanent"},
                    {"id": 26, "name": "Boudica", "class": "rider", "rarity": "r", "available": "permanent"},
                    {"id": 27, "name": "Ushiwakamaru", "class": "rider", "rarity": "r", "available": "permanent"},
                    {"id": 28, "name": "Alexander", "class": "rider", "rarity": "r", "available": "permanent"},
                    {"id": 29, "name": "Marie Antoinette", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 30, "name": "Martha", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 31, "name": "Medea", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 32, "name": "Gilles de Rais", "class": "caster", "rarity": "r", "available": "limited"},
                    {"id": 33, "name": "Hans Christian Andersen", "class": "caster", "rarity": "uc", "available": "permanent"},
                    {"id": 34, "name": "William Shakespeare", "class": "caster", "rarity": "uc", "available": "permanent"},
                    {"id": 35, "name": "Mephistopheles", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 36, "name": "Wolfgang Amadeus Mozart", "class": "caster", "rarity": "c", "available": "permanent"},
                    {"id": 37, "name": "Zhuge Liang (Lord El-Melloi II)", "class": "caster", "rarity": "ssr", "available": "permanent"},
                    {"id": 38, "name": "Cu Chulainn (Caster)", "class": "caster", "rarity": "r", "available": "limited"},
                    {"id": 39, "name": "Sasaki Kojiro", "class": "assassin", "rarity": "c", "available": "permanent"},
                    {"id": 40, "name": "Hassan of the Cursed Arm", "class": "caster", "rarity": "uc", "available": "permanent"},
                    {"id": 41, "name": "Stheno", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 42, "name": "Jing Ke", "class": "assassin", "rarity": "r", "available": "permanent"},
                    {"id": 43, "name": "Charles-Henri Sanson", "class": "assassin", "rarity": "uc", "available": "permanent"},
                    {"id": 44, "name": "Phantom of the Opera", "class": "assassin", "rarity": "uc", "available": "permanent"},
                    {"id": 45, "name": "Mata Hari", "class": "assassin", "rarity": "c", "available": "permanent"},
                    {"id": 46, "name": "Carmilla", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 47, "name": "Heracles", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 48, "name": "Lancelot", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 49, "name": "Lu Bu Fengxian", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 50, "name": "Spartacus", "class": "berserker", "rarity": "c", "available": "permanent"},
                    {"id": 51, "name": "Sakata Kintoki", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 52, "name": "Vlad III", "class": "berserker", "rarity": "ssr", "available": "permanent"},
                    {"id": 53, "name": "Asterios", "class": "berserker", "rarity": "c", "available": "permanent"},
                    {"id": 54, "name": "Caligula", "class": "berserker", "rarity": "uc", "available": "permanent"},
                    {"id": 55, "name": "Darius III", "class": "berserker", "rarity": "r", "available": "permanent"},
                    {"id": 56, "name": "Kiyohime", "class": "berserker", "rarity": "r", "available": "permanent"},
                    {"id": 57, "name": "Eric Bloodaxe", "class": "berserker", "rarity": "uc", "available": "permanent"},
                    {"id": 58, "name": "Tamamo Cat", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 59, "name": "Jeanne d'Arc", "class": "ruler", "rarity": "ssr", "available": "permanent"},
                    {"id": 60, "name": "Orion", "class": "archer", "rarity": "ssr", "available": "permanent"},
                    {"id": 61, "name": "Elizabeth Bathory (Halloween)", "class": "caster", "rarity": "sr", "available": "welfare"},
                    {"id": 62, "name": "Tamamo no Mae", "class": "caster", "rarity": "ssr", "available": "permanent"},
                    {"id": 63, "name": "David", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 64, "name": "Hektor", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 65, "name": "Francis Drake", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 66, "name": "Anne Bonny & Mary Read", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 67, "name": "Medea (Lily)", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 68, "name": "Okita Souji", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 69, "name": "Oda Nobunaga", "class": "archer", "rarity": "sr", "available": "welfare"},
                    {"id": 70, "name": "Scathach", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 71, "name": "Diarmuid Ua Duibhne", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 72, "name": "Fergus mac Roich", "class": "saber", "rarity": "r", "available": "permanent"},
                    {"id": 73, "name": "Altria Pendragon (Santa Alter)", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 74, "name": "Nursery Rhyme", "class": "caster", "rarity": "sr", "available": "permanent"},
                    {"id": 75, "name": "Jack the Ripper", "class": "assassin", "rarity": "ssr", "available": "permanent"},
                    {"id": 76, "name": "Mordred", "class": "saber", "rarity": "ssr", "available": "permanent"},
                    {"id": 77, "name": "Nikola Tesla", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 78, "name": "Altria Pendragon (Lancer Alter)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 79, "name": "Paracelsus von Hohenheim", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 80, "name": "Charles Babbage", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 81, "name": "Henry Jekyll & Hyde", "class": "assassin", "rarity": "r", "available": "permanent"},
                    {"id": 82, "name": "Frankenstein", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    //id 83 is Solomon
                    {"id": 84, "name": "Arjuna", "class": "archer", "rarity": "ssr", "available": "permanent"},
                    {"id": 85, "name": "Karna", "class": "lancer", "rarity": "ssr", "available": "permanent"},
                    {"id": 86, "name": "Mysterious Heroine X", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 87, "name": "Fionn mac Cumhaill", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 88, "name": "Brynhildr", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 89, "name": "Beowulf", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 90, "name": "Nero Cladius (Bride)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 91, "name": "Ryougi Shiki (Saber)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 92, "name": "Ryougi Shiki (Assassin)", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 93, "name": "Amakusa Shirou", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 94, "name": "Astolfo", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 95, "name": "Kid Gil", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 96, "name": "Edmond Dantes", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 97, "name": "Nightingale", "class": "berserker", "rarity": "ssr", "available": "permanent"},
                    {"id": 98, "name": "Cu Chulainn (Alter)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 99, "name": "Queen Medb", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 100, "name": "Helena Blavatsky", "class": "caster", "rarity": "sr", "available": "permanent"},
                    {"id": 101, "name": "Rama", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 102, "name": "Li Shuwen (Lancer)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 103, "name": "Thomas Edison", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 104, "name": "Geronimo", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 105, "name": "Billy the Kid", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 106, "name": "Jeanne d'Arc (Alter)", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 107, "name": "Angra Mainyu", "class": "avenger", "rarity": "angra", "available": "permanent"},
                    {"id": 108, "name": "Iskandar", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 109, "name": "EMIYA (Assassin)", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 110, "name": "Hassan of the Hundred Personas", "class": "assassin", "rarity": "r", "available": "permanent"},
                    {"id": 111, "name": "Irisviel (Dress of Heaven)", "class": "caster", "rarity": "sr", "available": "welfare"},
                    {"id": 112, "name": "Shuten-Douji", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 113, "name": "Xuanzang Sanzang", "class": "caster", "rarity": "ssr", "available": "permanent"},
                    {"id": 114, "name": "Minamoto no Raikou", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 115, "name": "Sakata Kintoki (Rider)", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 116, "name": "Ibaraki-Douji", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 117, "name": "Fuuma Koutarou", "class": "assassin", "rarity": "r", "available": "permanent"},
                    {"id": 118, "name": "Ozymandias", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 119, "name": "Altria Pendragon (Lancer)", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 120, "name": "Nitocris", "class": "caster", "rarity": "sr", "available": "permanent"},
                    {"id": 121, "name": "Lancelot (Saber)", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 122, "name": "Tristan", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 123, "name": "Gawain", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 124, "name": "Hassan of the Serenity", "class": "assassin", "rarity": "r", "available": "permanent"},
                    {"id": 125, "name": "Tawara Touta", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 126, "name": "Bedivere", "class": "saber", "rarity": "r", "available": "limited"},
                    {"id": 127, "name": "Leonardo da Vinci", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 128, "name": "Tamamo no Mae (Lancer)", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 129, "name": "Altria Pendragon (Archer)", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 130, "name": "Marie Antoinette (Caster)", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 131, "name": "Anne Bonny & Mary Read (Archer)", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 132, "name": "Mordred (Rider)", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 133, "name": "Scathach (Assassin)", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 134, "name": "Kiyohime (Lancer)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 135, "name": "Martha (Ruler)", "class": "ruler", "rarity": "sr", "available": "limited"},
                    {"id": 136, "name": "Illyasviel von Einzbern", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 137, "name": "Chloe von Einzbern", "class": "archer", "rarity": "sr", "available": "welfare"},
                    {"id": 138, "name": "Elizabeth Bathory (Brave)", "class": "saber", "rarity": "sr", "available": "welfare"},
                    {"id": 139, "name": "Cleopatra", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 140, "name": "Vlad III (Extra)", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 141, "name": "Jeanne d'Arc (Alter) (Santa Lily)", "class": "lancer", "rarity": "sr", "available": "welfare"},
                    {"id": 142, "name": "Ishtar", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 143, "name": "Enkidu", "class": "lancer", "rarity": "ssr", "available": "permanent"},
                    {"id": 144, "name": "Quetzalcoatl", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 145, "name": "Gilgamesh (Caster)", "class": "caster", "rarity": "sr", "available": "permanent"},
                    {"id": 146, "name": "Medusa (Lancer)", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 147, "name": "Gorgon", "class": "avenger", "rarity": "sr", "available": "limited"},
                    {"id": 148, "name": "Jaguar Warrior", "class": "lancer", "rarity": "r", "available": "limited"},
                    //id 149 is Tiamat
                    {"id": 150, "name": "Merlin", "class": "caster", "rarity": "ssr", "available": "limited"},
                    //id 151 is Goetia
                    //id 152 is Solomon
                    {"id": 153, "name": "Miyamoto Musashi", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 154, "name": "First Hassan", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 155, "name": "Mysterious Heroine X (Alter)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 156, "name": "James Moriarty", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 157, "name": "EMIYA (Alter)", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 158, "name": "Hessian Lobo", "class": "avenger", "rarity": "sr", "available": "permanent"},
                    {"id": 159, "name": "Yan Qing", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 160, "name": "Arthur Pendragon (Prototype)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 161, "name": "Hijikata Toshizo", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 162, "name": "Chacha", "class": "berserker", "rarity": "sr", "available": "welfare"},
                    {"id": 163, "name": "Meltryllis", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 164, "name": "Passionlip", "class": "alterego", "rarity": "sr", "available": "limited"},
                    {"id": 165, "name": "Suzuka Gozen", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 166, "name": "BB", "class": "mooncancer", "rarity": "sr", "available": "welfare"},
                    {"id": 167, "name": "Sessyoin Kiara", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    //id 168 is Beast III/R
                    {"id": 169, "name": "Scheherazade", "class": "caster", "rarity": "ssr", "available": "permanent"},
                    {"id": 170, "name": "Wu Zetian", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 171, "name": "Penthesilea", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 172, "name": "Christopher Columbus", "class": "rider", "rarity": "r", "available": "limited"},
                    {"id": 173, "name": "Sherlock Holmes", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 174, "name": "Paul Bunyan", "class": "berserker", "rarity": "c", "available": "welfare"},
                    {"id": 175, "name": "Nero Claudius (Caster)", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 176, "name": "Frankenstein (Saber)", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 177, "name": "Nitocris (Assassin)", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 178, "name": "Oda Nobunaga (Berserker)", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 179, "name": "Altria Pendragon (Rider Alter)", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 180, "name": "Helena Blavatsky (Archer)", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 181, "name": "Minamoto no Raikou (Lancer)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 182, "name": "Ishtar (Rider)", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 183, "name": "Parvati", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 184, "name": "Tomoe Gozen", "class": "archer", "rarity": "sr", "available": "permanent"},
                    {"id": 185, "name": "Mochizuki Chiyome", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 186, "name": "Houzouin Inshun", "class": "lancer", "rarity": "r", "available": "permanent"},
                    {"id": 187, "name": "Yagyu Munenori", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 188, "name": "Katou Danzo", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 189, "name": "Osakabehime", "class": "assassin", "rarity": "ssr", "available": "permanent"},
                    {"id": 190, "name": "Mecha Eli-chan", "class": "alterego", "rarity": "sr", "available": "welfare"},
                    {"id": 191, "name": "Mecha Eli-chan MK. II", "class": "alterego", "rarity": "sr", "available": "welfare"},
                    {"id": 192, "name": "Circe", "class": "caster", "rarity": "sr", "available": "permanent"},
                    {"id": 193, "name": "Nezha", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 194, "name": "Queen of Sheba", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 195, "name": "Abigail Williams", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 196, "name": "Ereshkigal", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 197, "name": "Altera the San(ta)", "class": "archer", "rarity": "sr", "available": "welfare"},
                    {"id": 198, "name": "Katsushika Hokusai", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 199, "name": "Semiramis", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 200, "name": "Asagami Fujino", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 201, "name": "Anastasia", "class": "caster", "rarity": "ssr", "available": "permanent"},
                    {"id": 202, "name": "Atalanta (Alter)", "class": "berserker", "rarity": "sr", "available": "permanent"},
                    {"id": 203, "name": "Avicebron", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 204, "name": "Antonio Salieri", "class": "avenger", "rarity": "r", "available": "limited"},
                    {"id": 205, "name": "Ivan the Terrible", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 206, "name": "Achilles", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 207, "name": "Chiron", "class": "archer", "rarity": "sr", "available": "permanent"},
                    {"id": 208, "name": "Sieg", "class": "caster", "rarity": "sr", "available": "welfare"},
                    {"id": 209, "name": "Okita Souji (Alter)", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 210, "name": "Okada Izou", "class": "assassin", "rarity": "r", "available": "limited"},
                    {"id": 211, "name": "Sakamoto Ryouma", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 212, "name": "Napoleon", "class": "archer", "rarity": "ssr", "available": "permanent"},
                    {"id": 213, "name": "Sigurd", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 214, "name": "Valkyrie", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 215, "name": "Scathach-Skadi", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 216, "name": "Jeanne d'Arc (Archer)", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 217, "name": "Ibaraki-Douji (Lancer)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 218, "name": "Ushiwakamaru (Assassin)", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 219, "name": "Jeanne d'Arc (Berserker Alter)", "class": "berserker", "rarity": "sr", "available": "welfare"},
                    {"id": 220, "name": "BB (Summer)", "class": "mooncancer", "rarity": "ssr", "available": "limited"},
                    {"id": 221, "name": "Queen Medb (Saber)", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 222, "name": "Mysterious Heroine XX", "class": "foreigner", "rarity": "sr", "available": "limited"},
                    {"id": 223, "name": "Diarmuid Ua Duibhne (Saber)", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 224, "name": "Sitonai", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 225, "name": "Shuten-Douji (Caster)", "class": "caster", "rarity": "sr", "available": "welfare"},
                    {"id": 226, "name": "Xiang Yu", "class": "berserker", "rarity": "ssr", "available": "permanent"},
                    {"id": 227, "name": "Prince of Lan Ling", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 228, "name": "Qin Liangyu", "class": "lancer", "rarity": "sr", "available": "permanent"},
                    {"id": 229, "name": "Qin Shi Huang", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 230, "name": "Yu Mei-ren", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 231, "name": "Red Hare", "class": "rider", "rarity": "r", "available": "limited"},
                    {"id": 232, "name": "Bradamante", "class": "lancer", "rarity": "ssr", "available": "permanent"},
                    {"id": 233, "name": "Quetzalcoatl (Samba/Santa)", "class": "ruler", "rarity": "sr", "available": "welfare"},
                    {"id": 234, "name": "Beni-Enma", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 235, "name": "Li Shuwen", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 236, "name": "Miyu Edelfelt", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 237, "name": "Murasaki Shikibu", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 238, "name": "Kingprotea", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 239, "name": "Kama", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    //id 240 is Beast III/L
                    {"id": 241, "name": "Sima Yi (Reines)", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 242, "name": "Astraea", "class": "ruler", "rarity": "sr", "available": "permanent"},
                    {"id": 243, "name": "Gray", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 244, "name": "Ganesha", "class": "mooncancer", "rarity": "ssr", "available": "permanent"},
                    {"id": 245, "name": "Lakshmibai", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 246, "name": "William Tell", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 247, "name": "Arjuna (Alter)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 248, "name": "Ashvattaman", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 249, "name": "Asclepius", "class": "caster", "rarity": "r", "available": "limited"},
                    {"id": 250, "name": "Demon King Nobunaga", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 251, "name": "Mori Nagayoshi", "class": "berserker", "rarity": "r", "available": "limited"},
                    {"id": 252, "name": "Nagao Kagetora", "class": "lancer", "rarity": "sr", "available": "welfare"},
                    {"id": 253, "name": "Leonardo da Vinci (Rider)", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 254, "name": "Jason", "class": "saber", "rarity": "c", "available": "permanent"},
                    {"id": 255, "name": "Paris", "class": "archer", "rarity": "uc", "available": "permanent"},
                    {"id": 256, "name": "Gareth", "class": "lancer", "rarity": "uc", "available": "permanent"},
                    {"id": 257, "name": "Bartholomew Roberts", "class": "rider", "rarity": "c", "available": "permanent"},
                    {"id": 258, "name": "Chen Gong", "class": "caster", "rarity": "uc", "available": "permanent"},
                    {"id": 259, "name": "Charlotte Corday", "class": "assassin", "rarity": "c", "available": "permanent"},
                    {"id": 260, "name": "Salome", "class": "berserker", "rarity": "uc", "available": "permanent"},
                    {"id": 261, "name": "Miyamoto Musashi (Berserker)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 262, "name": "Osakabehime (Archer)", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 263, "name": "Carmilla (Rider)", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 264, "name": "Katsushika Hokusai (Saber)", "class": "saber", "rarity": "sr", "available": "welfare"},
                    {"id": 265, "name": "Altria Pendragon (Ruler)", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 266, "name": "Mysterious Alter Ego Lambda", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 267, "name": "Okita J Souji", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 268, "name": "Space Ishtar", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 269, "name": "Calamity Jane", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 270, "name": "Astolfo (Saber)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 271, "name": "Nightingale (Santa)", "class": "archer", "rarity": "sr", "available": "welfare"},
                    {"id": 272, "name": "Super Orion", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 273, "name": "Mandricardo", "class": "rider", "rarity": "r", "available": "permanent"},
                    {"id": 274, "name": "Europa", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 275, "name": "Yang Guifei", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 276, "name": "Sei Shounagon", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 277, "name": "Odysseus", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 278, "name": "Dioscuri", "class": "saber", "rarity": "ssr", "available": "permanent"},
                    {"id": 279, "name": "Caenis", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 280, "name": "Romulus-Quirinus", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 281, "name": "Voyager", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 282, "name": "Kijyo Koyo", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 283, "name": "Utsumi Erice", "class": "lancer", "rarity": "sr", "available": "welfare"},
                    {"id": 284, "name": "Artoria Caster", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 285, "name": "Sessyoin Kiara (Moon Cancer)", "class": "mooncancer", "rarity": "ssr", "available": "limited"},
                    {"id": 286, "name": "Illyasviel von Einzbern (Archer)", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 287, "name": "Brynhildr (Berserker)", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 288, "name": "Yu Mei-ren (Lancer)", "class": "lancer", "rarity": "sr", "available": "welfare"},
                    {"id": 289, "name": "Abigail Williams (Summer)", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 290, "name": "Tomoe Gozen (Saber)", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 291, "name": "Murasaki Shikibu (Rider)", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 292, "name": "Himiko", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 293, "name": "Saito Hajime", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 294, "name": "Oda Nobukatsu", "class": "archer", "rarity": "c", "available": "limited"},
                    {"id": 295, "name": "Van Gogh", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 296, "name": "Nemo", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 297, "name": "Ashiya Douman", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 298, "name": "Watanabe no Tsuna", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 299, "name": "Ibuki-Douji", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 300, "name": "Vritra", "class": "lancer", "rarity": "ssr", "available": "permanent"},
                    {"id": 301, "name": "Karna (Santa)", "class": "saber", "rarity": "sr", "available": "welfare"},
                    {"id": 302, "name": "Senji Muramasa", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 303, "name": "Taira no Kagekiyo", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 304, "name": "Kiichi Hougen", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 305, "name": "Amor (Caren)", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 306, "name": "Galatea", "class": "berserker", "rarity": "ssr", "available": "permanent"},
                    {"id": 307, "name": "Miss Crane", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 308, "name": "Mysterious Idol X (Alter)", "class": "foreigner", "rarity": "sr", "available": "welfare"},
                    {"id": 309, "name": "Morgan", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 310, "name": "Barghest", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 311, "name": "Baobhan Sith", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 312, "name": "Melusine", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 313, "name": "Percival", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 314, "name": "Koyanskaya of Light", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 315, "name": "Habetrot", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 316, "name": "Oberon", "class": "pretender", "rarity": "ssr", "available": "limited"},
                    {"id": 317, "name": "Okita Souji (Saber Alter)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 318, "name": "Anastasia & Viy", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 319, "name": "Charlotte Corday (Caster)", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 320, "name": "Leonardo da Vinci (Ruler)", "class": "ruler", "rarity": "sr", "available": "welfare"},
                    {"id": 321, "name": "Kama (Avenger)", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 322, "name": "Caenis (Rider)", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 323, "name": "Sei Shounagon (Berserker)", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 324, "name": "Jacques de Molay", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 325, "name": "Zenobia", "class": "archer", "rarity": "sr", "available": "permanent"},
                    {"id": 326, "name": "Elizabeth Bathory (Cinderella)", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 327, "name": "Izumi no Okuni", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 328, "name": "Mysterious Ranmaru X", "class": "avenger", "rarity": "sr", "available": "welfare"},
                    {"id": 329, "name": "Sakamoto Ryouma (Lancer)", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 330, "name": "Martha (Santa)", "class": "caster", "rarity": "sr", "available": "welfare"},
                    {"id": 331, "name": "Tai Gong Wang", "class": "rider", "rarity": "ssr", "available": "permanent"},
                    {"id": 332, "name": "Dobrynya Nikitich", "class": "rider", "rarity": "sr", "available": "permanent"},
                    //id 333 is Beast IV
                    {"id": 334, "name": "Koyanskaya of Darkness", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 335, "name": "Hephaestion", "class": "pretender", "rarity": "sr", "available": "permanent"},
                    {"id": 336, "name": "Manannan mac Lir (Bazett)", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 337, "name": "Trung Sisters", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 338, "name": "Taisui Xingjun", "class": "alterego", "rarity": "sr", "available": "welfare"},
                    {"id": 339, "name": "Super Bunyan", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 340, "name": "Daikokuten", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 341, "name": "Mary Anning", "class": "lancer", "rarity": "c", "available": "limited"},
                    {"id": 342, "name": "Constantine IX", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 343, "name": "Charlemagne", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 344, "name": "Roland", "class": "saber", "rarity": "sr", "available": "permanent"},
                    {"id": 345, "name": "Kriemhild", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 346, "name": "James Moriarty (Ruler)", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 347, "name": "Don Quixote", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 348, "name": "Zhang Jiao", "class": "caster", "rarity": "r", "available": "permanent"},
                    {"id": 349, "name": "Kyokutei Bakin", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 350, "name": "Minamoto no Tametomo", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 351, "name": "Archetype: Earth", "class": "mooncancer", "rarity": "ssr", "available": "limited"},
                    {"id": 352, "name": "Xu Fu", "class": "alterego", "rarity": "r", "available": "permanent"},
                    {"id": 353, "name": "Lady Avalon", "class": "pretender", "rarity": "ssr", "available": "limited"},
                    {"id": 354, "name": "Gareth (Saber)", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 355, "name": "Ibuki Douji (Berserker)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 356, "name": "Utsumi Erice (Avenger)", "class": "avenger", "rarity": "sr", "available": "limited"},
                    {"id": 357, "name": "Scathach-Skadi (Ruler)", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 358, "name": "Wu Zetian (Caster)", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 359, "name": "Thrúd (Assassin)", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 360, "name": "Hildr (Assassin)", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 361, "name": "Ortlinde (Assassin)", "class": "assassin", "rarity": "sr", "available": "welfare"},
                    {"id": 362, "name": "Sen no Rikyu", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 363, "name": "Yamanami Keisuke", "class": "saber", "rarity": "sr", "available": "limited"},
                    {"id": 364, "name": "Iyo", "class": "ruler", "rarity": "sr", "available": "welfare"},
                    {"id": 365, "name": "Huyan Zhuo", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 366, "name": "Huang Feihu", "class": "rider", "rarity": "sr", "available": "permanent"},
                    {"id": 367, "name": "Nine-Tattoo Dragon Eliza", "class": "pretender", "rarity": "sr", "available": "welfare"},
                    {"id": 368, "name": "Britomart", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 369, "name": "Grigori Rasputin", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 370, "name": "Nitocris (Alter)", "class": "avenger", "rarity": "ssr", "available": "permanent"},
                    {"id": 371, "name": "Tezcatlipoca", "class": "assassin", "rarity": "ssr", "available": "limited"},
                    {"id": 372, "name": "Tenochtitlan", "class": "pretender", "rarity": "sr", "available": "permanent"},
                    {"id": 373, "name": "Kukulkan", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 374, "name": "Popess Johanna", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 375, "name": "Takasugi Shinsaku", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 376, "name": "Larva/Tiamat", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 377, "name": "Sodom's Beast/Draco", "class": "beast", "rarity": "ssr", "available": "limited"},
                    {"id": 378, "name": "Locusta", "class": "assassin", "rarity": "sr", "available": "limited"},
                    {"id": 379, "name": "Sétanta", "class": "saber", "rarity": "sr", "available": "welfare"},
                    {"id": 380, "name": "Kashin Koji", "class": "assassin", "rarity": "ssr", "available": "permanent"},
                    {"id": 381, "name": "Bhima", "class": "lancer", "rarity": "ssr", "available": "limited"},
                    {"id": 382, "name": "Duryodhana", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 383, "name": "Durga", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 384, "name": "Medusa (Saber)", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 385, "name": "Aesc the Savior", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 386, "name": "Artoria Caster (Berserker)", "class": "berserker", "rarity": "ssr", "available": "limited"},
                    {"id": 387, "name": "Suzuka Gozen (Summer Vacation)", "class": "rider", "rarity": "sr", "available": "limited"},
                    {"id": 388, "name": "Chloe von Einzbern (Avenger)", "class": "avenger", "rarity": "sr", "available": "limited"},
                    {"id": 389, "name": "Cnoc na Riabh Yaraan-doo", "class": "foreigner", "rarity": "sr", "available": "welfare"},
                    {"id": 390, "name": "Mélusine (Ruler)", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 391, "name": "UDK-Barghest", "class": "archer", "rarity": "sr", "available": "limited"},
                    {"id": 392, "name": "Cait Cú Cerpriestess", "class": "pretender", "rarity": "sr", "available": "limited"},
                    {"id": 393, "name": "Wandjina", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 394, "name": "Ptolemaios", "class": "archer", "rarity": "ssr", "available": "limited"},
                    {"id": 395, "name": "Sugitani Zenjubo", "class": "archer", "rarity": "r", "available": "permanent"},
                    {"id": 396, "name": "Theseus", "class": "saber", "rarity": "r", "available": "permanent"},
                    {"id": 397, "name": "Takeda Shingen", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 398, "name": "Nakagura Shinpachi", "class": "berserker", "rarity": "sr", "available": "limited"},
                    {"id": 399, "name": "Saika Magoichi", "class": "archer", "rarity": "sr", "available": "welfare"},
                    {"id": 400, "name": "Uesugi Kenshin", "class": "ruler", "rarity": "ssr", "available": "limited"},
                    {"id": 401, "name": "Nemo (Santa)", "class": "rider", "rarity": "sr", "available": "welfare"},
                    {"id": 402, "name": "Yamato Takeru", "class": "saber", "rarity": "ssr", "available": "limited"},
                    {"id": 403, "name": "Minamoto no Raikou/Ushi Gozen", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 404, "name": "Yui Shousetsu", "class": "caster", "rarity": "sr", "available": "limited"},
                    {"id": 405, "name": "Miyamoto Iori", "class": "saber", "rarity": "sr", "available": "welfare"},
                    {"id": 406, "name": "Andromeda", "class": "rider", "rarity": "ssr", "available": "limited"},
                    {"id": 407, "name": "Marie Antoinette (Alter)", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 408, "name": "Hassan of the Shining Star", "class": "assassin", "rarity": "sr", "available": "permanent"},
                    {"id": 409, "name": "King of the Cavern, Monte Cristo", "class": "avenger", "rarity": "ssr", "available": "limited"},
                    {"id": 410, "name": "Alessandro di Cagliostro", "class": "pretender", "rarity": "sr", "available": "limited"},
                    // id 411 and 412 are spoilers in NA
                    {"id": 413, "name": "Aozaki Aoko", "class": "foreigner", "rarity": "ssr", "available": "limited"},
                    {"id": 414, "name": "Shizuki Soujuurou", "class": "berserker", "rarity": "sr", "available": "welfare"},
                    {"id": 415, "name": "Kuonji Alice", "class": "caster", "rarity": "ssr", "available": "limited"},
                    {"id": 416, "name": "Azumi no Isora (Hibiki & Chikagi)", "class": "alterego", "rarity": "ssr", "available": "limited"},
                    {"id": 417, "name": "Space Ereshkigal", "class": "beast", "rarity": "ssr", "available": "limited"},
                    {"id": 418, "name": "Mysterious Executor C.I.E.L", "class": "mooncancer", "rarity": "ssr", "available": "limited"},
                    {"id": 419, "name": "Dobrynya Nikitich (Lancer)", "class": "lancer", "rarity": "sr", "available": "limited"},
                    {"id": 420, "name": "Xu Fu (Avenger)", "class": "avenger", "rarity": "sr", "available": "limited"},
                    {"id": 421, "name": "BB Dubai", "class": "mooncancer", "rarity": "ssr", "available": "limited"},
                    {"id": 422, "name": "Tenochtitlan (Moon Cancer)", "class": "mooncancer", "rarity": "sr", "available": "limited"},
                    {"id": 423, "name": "Mysterious Heroine XX (Alter)", "class": "foreigner", "rarity": "srr", "available": "limited"}]

function compare_name( a, b )
  {
  if ( a.name.toLowerCase() < b.name.toLowerCase()){
    return -1;
  }
  if ( a.name.toLowerCase() > b.name.toLowerCase()){
    return 1;
  }
  return 0;
}
                    
servantList.sort(compare_name);
